### ISSUE TITLE
option for different names of output files

### ISSUE THREAD

**Issue by carltape** [uafgeotools/pysep#7]
Some applications may require a shorter file name than the ones we're using. For example sac2db seems to require lengths that are no more than 32 characters (why?!). Our typical file name like this
20170331131408312.ZE.WFLS..HH.z
includes the origin time to milliseconds. It is close to 32 char -- so a location code might put it over.
We might want a variable like USE_SHORT_FILENAME as a workaround. In that case, the full origin time would be "saved" within the directory name, but then the file names would be YYYYMMDD or something similar. No action needed right now -- just keep this in mind.

**Comment by bch0w** [comment]
By default filenames are pretty long (e.g., 2009-04-07T201255_ANCHORAGE), but Users can use the `--legacy_naming` flag to get SAC appropriate file names
