### ISSUE TITLE
create variable to run tau-p

### ISSUE THREAD

**Issue by carltape** [uafgeotools/pysep#8]
We need a variable (USE_TAUP?) so that the user will specify whether to run tau-p to get P and S times and incident angles. By default, I think we do not want this to be set. Thanks.

**Comment by bch0w** [comment]
At the moment TauP travel times and incident angles are retrieved by default for AK135. If the User sets the YAML parameter file parameter `taup_model` to 'null', they can turn off this feature and PySEP will skip over TauP picks
